// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Sekiro();
Q_GHS_KEEP_REFERENCE(qml_register_types_Sekiro)

class SekiroPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    SekiroPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Sekiro;
        Q_UNUSED(registration)
    }
};



#include "Sekiroplugin_SekiroPlugin.moc"
